name: fms_ditu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add plugins here
  cupertino_icons: ^1.0.2
  group_button: ^4.8.0
  firebase_auth:
  firebase_core:
  firebase_storage:
  google_nav_bar: ^5.0.6
  url_launcher: ^6.0.20
  line_icons: ^2.0.1
  card_swiper: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  whatsapp_unilink: ^2.0.1+1
#  flutter_open_whatsapp: ^0.1.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic


